services:
  db:
    image: postgres:16
    container_name: nugasinbandung-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nugasinbandung-network

  backend:
    build: ./backend
    container_name: nugasinbandung-backend
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - nugasinbandung-network

  frontend:
    build: ./frontend
    container_name: nugasinbandung-frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - nugasinbandung-network

volumes:
  postgres_data:

networks:
  nugasinbandung-network:
    driver: bridge